version: "3.8"

services:
  dev-db:
    image: postgres:14
    container_name: dev-db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev-network

  test-db:
    image: postgres:14
    container_name: test-db
    env_file:
      - .env
    ports:
      - "5435:5432"
    networks:
      - dev-network

volumes:
  db_data:

networks:
  dev-network:
    driver: bridge
