export enum InterestReason {
    PRICE = 'PRICE',
    FEATURES = 'FEATURES',
    SUPPORT = 'SUPPORT',
    SCALABILITY = 'SCALABILITY',
    SECURITY = 'SECURITY',
    COMPLIANCE = 'COMPLIANCE',
    ROI = 'ROI',
    USER_EXPERIENCE = 'USER_EXPERIENCE',
    EFFICIENCY = 'EFFICIENCY',
    AUTOMATION = 'AUTOMATION',
    PERSONALIZATION = 'PERSONALIZATION',
    INTEGRATION = 'INTEGRATION',
    QUALITY = 'QUALITY',
    CUSTOMER_SATISFACTION = 'CUSTOMER_SATISFACTION',
    TIME_SAVINGS = 'TIME_SAVINGS',
    OTHER = 'OTHER'
}