export enum LeadSource {
    REFERRAL = 'REFERRAL',
    ORGANIC_SEARCH = 'ORGANIC_SEARCH',
    SOCIAL_MEDIA = 'SOCIAL_MEDIA',
    PAID_AD = 'PAID_AD',
    EVENT = 'EVENT',
    COLD_OUTREACH = 'COLD_OUTREACH',
    PARTNER = 'PARTNER',
    CONFERENCE = 'CONFERENCE',
    OTHER = 'OTHER'
}
